### ISSUE TITLE
None-Linear Arithmetic with quantifiers

### ISSUE THREAD

**Issue by kgoyal40** [SRI-CSL/yices2_python_bindings#1]
Hi,

I have an application which requires me to use ForAll quantifier over non-linear Arithmetic. I am aware that yices did not support formulas like these earlier and was under the impression that this functionality is being developed. Can you please let me know if this has been added to the solver?

Kshitij

**Comment by ianamason** [comment]
I am closing this, because it has nothing to do with the python bindings, and you opened a duplicate issue at the yices2 page. Which is the right place to ask the question.
