### ISSUE TITLE
CDLL(libyices.so.2.6) raised libyices.so.2.6

### ISSUE THREAD

**Issue by ascandal** [SRI-CSL/yices2_python_bindings#4]
I got this warning in docker ubuntu 20.04 with yices source code build,

`CDLL(libyices.so.2.6) raised libyices.so.2.6: cannot open shared object file: No such file or directory.`

`ldconfig` fixed for me.

suggest to add to readme under yices_python_info bullet

  - Note: On Linux, if the warning message appears `CDLL(libyices.so.2.6) raised libyices.so.2.6: cannot open shared object file: No such file or directory.`, then try running:
    ```
    sudo ldconfig
    ```

**Comment by ianamason** [comment]
I'm inclined just to let this issue do that job. This is really the purview of CDLL in my opinion.
But thanks for creating it, and solving it at the same time.
